spring.application.name=jwt_project

spring.datasource.url=jdbc:mysql://localhost:3306/jwt_user
spring.datasource.username=root
spring.datasource.password=
#
frontend.url=${FRONTEND_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=aditya
spring.security.user.password=adi123
jwt.secret=mysupersecretkeymysupersehhsbdjsahsvdjavdadmhey12345
jwt.expiration=3600000
server.port=8085

